version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Berlin"
    assignees:
      - "bierdosenhalter"
    reviewers:
      - "bierdosenhalter"
    commit-message:
      prefix: "npm"
      include: "scope"
